"""
API route definitions for the FastAPI application.
"""
from fastapi import APIRouter, HTTPException, Depends
from typing import List, Dict, Any

from app.schemas.schema import ReplyRequest, ReplyResponse
from app.logic import generate_reply
from app.db.database import Database


router = APIRouter()


@router.post("/reply", response_model=ReplyResponse)
async def create_reply(request: ReplyRequest):
    """
    Generate a human-like reply to a social media post.
    
    - **platform**: The social media platform (twitter, linkedin, etc.)
    - **post_text**: The text content of the post to reply to
    - **context**: Optional additional context about the post
    - **include_analysis**: Whether to include post analysis in the response
    
    Returns a response with the generated reply and metadata.
    """
    try:
        reply_result = await generate_reply(
            platform=request.platform,
            post_text=request.post_text,
            context=request.context,
            include_analysis=request.include_analysis
        )
        
        return ReplyResponse(**reply_result)
        
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate reply: {str(e)}"
        )


@router.get("/replies/recent", response_model=List[ReplyResponse])
async def get_recent_replies(platform: str = None, limit: int = 10):
    """
    Get recent replies generated by the system.
    
    - **platform**: Optional platform to filter by
    - **limit**: Maximum number of replies to return (default: 10)
    
    Returns a list of recent replies.
    """
    if limit > 50:
        limit = 50  # Cap the limit to prevent excessive requests
        
    replies = await Database.get_recent_replies(platform=platform, limit=limit)
    
    return [ReplyResponse(**reply) for reply in replies]


@router.get("/health")
async def health_check():
    """
    Health check endpoint to verify the API is working.
    """
    return {"status": "ok", "service": "Social Media Reply Generator API"}